In [19]:
# read n spaced seperated integers from user and find the sum of middle digits
#987 654 389 876 531
n=int(input("enter the no of integers:"))
a=list(map(str,input().split()[:n]))
s=0
for i in a:
    s=s+int(i[len(i)//2])

print(s)

enter the no of integers:5
987 654 389 876 531
31


# Data Analysis

- The meaningful information said to be data
- Types of data in realtime/devices
    - .txt,.doc,.xls,.ppt,.mp3,.mp4 etc
- Types of Data in realtime
    1. Quantitative and
        - Represents the size/volume of data
        - Discrete and ContinuouS
            - This type of data is fixed/constant
                - Ex: numbers on die:varies from 1 to 6
                    ~ distance,color,nationality,size etc
            - Continuous data means the value/data is continuous
                - height,weight & hours
    2. Qualitative
        - Data is observed and placed in terms of catergory
            - Ex: Data Submission in Feedback form
- Data in Statistics
    - Nominal,Ordinal,Interval and Ratio
        - Nominal means data is categorized on the basis of names
            - Ex: Nationality,Color,Gender
        - Ordinal means data is based upon the order of values
            - Feedback form
        - Interval means a range of data values
            - time interval in clock :2:15 is in b/w 2&3
        - Raio means data is meaningfuly added,subtracted,mutiplied or divided

In [2]:
import numpy as np
dir(np)#directory of numpy

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [7]:
np.__version__ 

'1.20.1'

### array creation()
- array() is the submodule in numpy module
- syntax np.array(iterable)


In [8]:
print(np.array([1,2,3,4,5,6])) # homogeneous data structure

[1 2 3 4 5 6]


In [9]:
ab=np.array((1,2,3,4,5))#tuple can be converted in array
print(ab)

[1 2 3 4 5]


In [10]:
# array decleration
ar=np.array([45.6,65,76.6,89.2],dtype="float")
print(ar)

[45.6 65.  76.6 89.2]


In [11]:
# dtype is used to specify the data type in the array
ar=np.array([45.6,65,76.6,89.2],dtype="int")
print(ar)

[45 65 76 89]


In [12]:
ar=np.array([45.6,65,76.6,89.2],dtype="str")
print(ar)

['45.6' '65' '76.6' '89.2']


In [13]:
ar=np.array([45.6,65,76.6,89.2],dtype="float")
print(ar)

[45.6 65.  76.6 89.2]


In [16]:
# for getting an array of consequtive numbers
print(np.array(range(1,3)))

[1 2]


In [18]:
#for creating 2d or 3d array
li=np.array([[10,11,12],[5,6,7]])#size 2x3
print(li)

[[10 11 12]
 [ 5  6  7]]


In [24]:
print(li.shape)#(row,column)
print(li.dtype)#data typeof values in array
print(li.itemsize)#size of variable in array

(2, 3)
int32
4


In [28]:
# 3 dimensional array
d3=np.array([[[3,4,5],[5,6,7]],[[4,6,"e"],[9,3,"o"]]])
d3.shape#(2,2,3) (no of arrays,rows,col)


(2, 2, 3)

In [39]:
# ndmin for giving the dimension of array
d4=np.array([1,2,3,4],ndmin=32)# A maximum upto 32 
print(d4)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


In [40]:
# eye for indentity matrix of size n
d1=np.eye(4)
d1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
# zeros for creating a null matrix
d1=np.zeros((2,3),dtype="int")
print(d1)

[[0 0 0]
 [0 0 0]]


In [44]:
d1.size

6

In [51]:
d1=np.eye(4,5)
print(d1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [56]:
o=np.ones((4,5),dtype="int")#to get an array filed with 1
print(o)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [61]:
o1=np.full((3,4),3)
print(o1)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [82]:
o1.fill(4)
o1.dtype="float"
print(o1)

[[4. 4.]
 [4. 4.]
 [4. 4.]]


In [86]:
#creating an array with linear space
ln=np.linspace(10,200,13)
ln

array([ 10.        ,  25.83333333,  41.66666667,  57.5       ,
        73.33333333,  89.16666667, 105.        , 120.83333333,
       136.66666667, 152.5       , 168.33333333, 184.16666667,
       200.        ])

###  creating array with arange()

In [87]:
# creating array with arange
ar=np.arange(25)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [89]:
ar=np.arange(1,23)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [95]:
ar=np.arange(24,1,-2)
len(ar)

12

In [98]:
#converting existed array into 2d array using 
#using reshape()
ar=ar.reshape(3,4)
print(ar)

[[24 22 20 18]
 [16 14 12 10]
 [ 8  6  4  2]]


In [101]:
ar=ar.reshape(4,3)
print(ar)

[[24 22 20]
 [18 16 14]
 [12 10  8]
 [ 6  4  2]]


In [106]:
ar=np.arange(1,41)
ar=ar.reshape(5,8)
print(ar)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]]


### random() module in numpy
- Used to generate random integers in  range
- random.randint()

In [6]:
np.random.randint(60,500)#ever time we get different value

170

In [17]:
#to get multiple random values 
# an array of multiple values is returned
ri=np.random.randint(60,1000,8)#(lower,upper,no of integers we want)
ri=ri.reshape(2,4)
ri

array([[771, 542, 683, 229],
       [608, 348, 310, 811]])

In [18]:
ri.ndim

2

In [21]:
lw=10
up=15
rq=np.random.randint(lw,up,2)
rq


array([14, 10])

In [23]:
np.random.random((2,3))#b/w 0 and 1 of size(2,3)

array([[0.67415655, 0.84477137, 0.42125484],
       [0.30678487, 0.84434566, 0.12812899]])

In [25]:
np.random.rand(4,3)#b/w 0 and 1

array([[0.62131747, 0.94176095, 0.89922509],
       [0.31349169, 0.62383786, 0.46859525],
       [0.71760536, 0.57379565, 0.74995072],
       [0.96241219, 0.47973492, 0.05274527]])

In [24]:
np.random.randn(2,3)#b/w -1 and 1 of size (2,3)

array([[ 0.55642132,  0.7409029 ,  0.23325781],
       [ 0.21756429, -0.53302038,  0.97810217]])

### Acessing the array elements
- using index
- index is of 3 types 
- +ve indexing -ve indexing and fancy indexing
   - +ve index:traverse from left to right 
   - starts for 0 and ends at len(l)-1
   - -ve indexL:traverse from right to left
   - starts from -1 and upto - infinity
   - fancy:condition based index

In [29]:
l1=np.array([[1,2,3],[2,3,4]])
l2=np.array([[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [2, 3, 4]])

In [89]:
r=np.random.randint(50,200,25).reshape(5,-1)
print(r)

[[179 166 182  80  75]
 [136  96 168  97 139]
 [119  92  83  68 158]
 [ 75 172  90 196  55]
 [169 193  79 175  93]]


In [35]:
r1=np.arange(50,150,10).reshape(-1,2)
r1

array([[ 50,  60],
       [ 70,  80],
       [ 90, 100],
       [110, 120],
       [130, 140]])

In [98]:
# acessing array elemnts
arn=np.arange(50,100,2).reshape(-3,5)
arn

array([[50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [95]:
arn[::2]

array([[50, 52, 54, 56, 58],
       [70, 72, 74, 76, 78],
       [90, 92, 94, 96, 98]])

In [58]:
arn[::2,1:3]

array([[52, 54],
       [72, 74],
       [92, 94]])

In [59]:
for i in arn[::2,1:3]:
    for x in i:
        if x%2==0:
            print(x)

52
54
72
74
92
94


In [64]:
# alteranating rows and columns elements 
# extract a sub array of the upper condition
arn[::2,::2]

array([[50, 54, 58],
       [70, 74, 78],
       [90, 94, 98]])

In [65]:
arn[-3:-1]

array([[70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88]])

In [71]:
arn[arn<100]

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

In [85]:
# to perform all arthimetic operation on array
print(arn+r,end=" ")
print(arn/4,end=" ")
print(arn,end=" ")

[[233 175 181 190 121]
 [248 157 218 262 261]
 [195 203 161 181 189]
 [140 250 252 257 230]
 [252 244 211 224 149]] [[12.5 13.  13.5 14.  14.5]
 [15.  15.5 16.  16.5 17. ]
 [17.5 18.  18.5 19.  19.5]
 [20.  20.5 21.  21.5 22. ]
 [22.5 23.  23.5 24.  24.5]] [[50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]] 

In [77]:
r.dot(arn)

array([[41810, 43070, 44330, 45590, 46850],
       [58930, 60582, 62234, 63886, 65538],
       [38590, 39708, 40826, 41944, 43062],
       [51300, 52718, 54136, 55554, 56972],
       [40240, 41460, 42680, 43900, 45120]])

In [91]:
r.mean()

125.4

In [90]:
r.min()

55

In [92]:
r.max()

196

In [96]:
sum(arn)

array([350, 360, 370, 380, 390])

In [101]:
arn[:,0].sum()

350

In [105]:
# scientific communication
# logarithims and exponentials
np.log(10)#fo

1.0

In [110]:
np.log([1,2,3,4])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [114]:
np.log2(10)

3.321928094887362

In [115]:
np.log(10)/np.log(7)

1.1832946624549385

In [116]:
np.exp(np.log(1))

1.0

### vectorized functions in numpy

In [118]:
l1,l2=[1,2,6],[2,5,4]
n=[]
for a,b in zip(l1,l2):
    if a>b:
        n.append(a)
    else:
        n.append(b)
print(n)

[2, 5, 6]


In [124]:
def greater(a,b):
    if a>b:return a
    else:return b

g=np.vectorize(greater)
print(g((1,2,3),(9,0,4)))

[9 2 4]
